sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t gbe/malc -f Dockerfile_Debian .

script:
  - docker run --rm=true -v $HOME:$HOME:rw gbe/malc /bin/bash -c "cd $PWD && ./genmakeall"
  - file ./genmakeall
