sudo: required

language: c

services:
  - docker

matrix:
  allow_failures:
    - env:
        - "DOCKER_OS=Debian"
        - "DOCKER_TAG=debian"
      services:
        - docker
    - env:
        - "DOCKER_OS=Debian32"
        - "DOCKER_TAG=debian32"
      services:
        - docker
  include:
    - env:
        - "DOCKER_OS=Centos"
        - "DOCKER_TAG=centos"
      services:
        - docker
    - env:
        - "DOCKER_OS=OpenSuse"
        - "DOCKER_TAG=opensuse"
      services:
        - docker

before_install:
  - docker build -t gbe/malc-$DOCKER_TAG -f Dockerfile_$DOCKER_OS .

script:
  - docker run --rm=true -v $HOME:$HOME:rw gbe/malc-$DOCKER_TAG /bin/bash -c "cd $PWD && ./bin/update_known_projects.sh /usr/local/bin/zproject_known_projects.xml && ./genmakeall"
  - file ./genmakeall
